/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ClienteControle;
import controle.ServicoControle;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

import net.sf.jasperreports.swing.JRViewer;
import util.Conexao;

/**
 *
 * @author nato-
 */
public class telaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaprincipal
     */
    private ServicoControle servicoControle;
    private ClienteControle clienteControle;
    //private EntityManager em = null;

    public telaprincipal() {
        initComponents();

        this.servicoControle = new ServicoControle();
        this.clienteControle = new ClienteControle();
        //this.em = Conexao.getConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitulo = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelBotoes = new javax.swing.JPanel();
        btn_prestar_servico = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        labLogoEmpresa = new javax.swing.JLabel();
        labLogMotoTaxi1601 = new javax.swing.JLabel();
        jPanelFrase = new javax.swing.JPanel();
        jLabelFrase = new javax.swing.JLabel();
        btnImprimirServicosPrestados = new javax.swing.JButton();
        btMostrarServico = new javax.swing.JButton();
        btnImprimirRelatorioDeClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moto taxi 1601 O AMARELINHO DA CIDADE");
        setResizable(false);

        labTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitulo.setText("SISTEMA PARA GERENCIAR SERVIÇOS EFETUADOS A GENU-IN");
        labTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelPrincipal.setBorder(new javax.swing.border.MatteBorder(null));

        jPanelBotoes.setLayout(new java.awt.GridLayout(1, 0));

        btn_prestar_servico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_prestar_servico.setText("prestar serviço");
        btn_prestar_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prestar_servicoActionPerformed(evt);
            }
        });
        jPanelBotoes.add(btn_prestar_servico);

        btnFuncionario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFuncionario.setText("Funcionário");
        btnFuncionario.setToolTipText("clik aqui  para ver o mototaxistas que presta o serviços.");
        btnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioActionPerformed(evt);
            }
        });
        jPanelBotoes.add(btnFuncionario);

        btnCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setToolTipText("Clik aqui para ver os Funcionarios da Genu-in que solicita os serviços.");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanelBotoes.add(btnCliente);

        labLogoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log_genu-in.jpg"))); // NOI18N

        labLogMotoTaxi1601.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log.png"))); // NOI18N

        jPanelFrase.setBackground(new java.awt.Color(204, 255, 204));
        jPanelFrase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelFrase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelFrase.setText("               Parceria & Comprometimento");

        javax.swing.GroupLayout jPanelFraseLayout = new javax.swing.GroupLayout(jPanelFrase);
        jPanelFrase.setLayout(jPanelFraseLayout);
        jPanelFraseLayout.setHorizontalGroup(
            jPanelFraseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFraseLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelFrase, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );
        jPanelFraseLayout.setVerticalGroup(
            jPanelFraseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFraseLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btnImprimirServicosPrestados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnImprimirServicosPrestados.setText("Imprimir Relatório de Serviços Prestados");
        btnImprimirServicosPrestados.setToolTipText("clike para gerar um o relatório de serviço...");
        btnImprimirServicosPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirServicosPrestadosActionPerformed(evt);
            }
        });

        btMostrarServico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btMostrarServico.setText("Mostrar Serviços");
        btMostrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarServicoActionPerformed(evt);
            }
        });

        btnImprimirRelatorioDeClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnImprimirRelatorioDeClientes.setText("Imprimir Relatório de Clientes");
        btnImprimirRelatorioDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRelatorioDeClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(labLogoEmpresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelFrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labLogMotoTaxi1601))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(btnImprimirServicosPrestados, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnImprimirRelatorioDeClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMostrarServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labLogoEmpresa)
                    .addComponent(labLogMotoTaxi1601))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimirServicosPrestados)
                    .addComponent(btnImprimirRelatorioDeClientes)
                    .addComponent(btMostrarServico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        //  Telacliente tela = new Telacliente();
        // this.dispose(); // esconde a tela
        //  tela.setVisible(true);

        TelaManutencaoCliente tela = new TelaManutencaoCliente(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaManutencaoFuncionario mf = new TelaManutencaoFuncionario(this, true);
        mf.setVisible(true);
    }//GEN-LAST:event_btnFuncionarioActionPerformed

    private void btn_prestar_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prestar_servicoActionPerformed
        // TODO add your handling code here:
        TelaServico ts = new TelaServico(this, true);
        ts.setVisible(true);
    }//GEN-LAST:event_btn_prestar_servicoActionPerformed

    private void btMostrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarServicoActionPerformed
        // TODO add your handling code here:
        TelaManutencaoServico ms = new TelaManutencaoServico(this, true);
        ms.setVisible(true);
    }//GEN-LAST:event_btMostrarServicoActionPerformed

    private void btnImprimirServicosPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirServicosPrestadosActionPerformed
        // TODO add your handling code here:

        TelaFiltroRelatorio tela = new TelaFiltroRelatorio(this, true);
        tela.setVisible(true);
//        try {
//            //teste
//            String relatorio = "/relatorio/ServicosPrestados.jasper";
//             InputStream stream = getClass().getResourceAsStream(relatorio);//PARA FUNCIONAR NO ARQUIVO .JAR TEM QUE USAR ESTA LINHA
//            //JasperPrint relatorioPreenchido = JasperFillManager.fillReport(relatorio,null,new JRBeanCollectionDataSource(controle.listarTodos()));
//            JasperPrint relatorioPreenchido = JasperFillManager.fillReport(stream, null, new JRBeanCollectionDataSource(servicoControle.listarTodos()));
//
//            JDialog tela = new JDialog(this,"Relatório de Serviços Prestados");
//         //teste
//            tela.setSize(1024, 768);
//            tela.setLocale(null);
//            tela.setLocationRelativeTo(null);
//            JRViewer painel = new JRViewer(relatorioPreenchido);
//            tela.getContentPane().add(painel);
//            System.out.println("Abrindo o relatorio agora...");
//            tela.setVisible(true);
//  
//        } catch (JRException ex) {
//            
//            Logger.getLogger(TelaManutencaoServico.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(this, "Erro ao gerar o relatório ");
//
//        }
    }//GEN-LAST:event_btnImprimirServicosPrestadosActionPerformed

    private void btnImprimirRelatorioDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRelatorioDeClientesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "LEGAL!!! RELATORIO ESTA EM DESENVOLVIMENTO!!!");
//        try {
//            //teste
//            String relatorio = "/relatorio/Relatorio_GENU.jasper";
//            InputStream stream = getClass().getResourceAsStream(relatorio);//PARA FUNCIONAR NO ARQUIVO .JAR TEM QUE USAR ESTA LINHA
//            //JasperPrint relatorioPreenchido = JasperFillManager.fillReport(relatorio,null,new JRBeanCollectionDataSource(controle.listarTodos()));
//            JasperPrint relatorioPreenchido = JasperFillManager.fillReport(stream, null, new JRBeanCollectionDataSource(clienteControle.listarTodos()));
//
//            JDialog tela = new JDialog(this, "Relatório de Clientes");
//            //fim teste
//
//            tela.setSize(1024, 768);
//            tela.setLocale(null);
//            tela.setLocationRelativeTo(null);
//            JRViewer painel = new JRViewer(relatorioPreenchido);
//            tela.getContentPane().add(painel);
//            System.out.println("Abrindo o relatório");
//            tela.setVisible(true);
//            // JasperPrintManager.printPage(relatorioPreenchido, 0, false);//para enviar para impressora
//            //true abre janela de impressao, false imprime direto
//
//        } catch (JRException e) {
//            Object ex = null;
//            Logger.getLogger(TelaManutencaoServico.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null, "Erro ao gerar o relatório " + e);
//
//        }
    }//GEN-LAST:event_btnImprimirRelatorioDeClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMostrarServico;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnImprimirRelatorioDeClientes;
    private javax.swing.JButton btnImprimirServicosPrestados;
    private javax.swing.JButton btn_prestar_servico;
    private javax.swing.JLabel jLabelFrase;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelFrase;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JLabel labLogMotoTaxi1601;
    private javax.swing.JLabel labLogoEmpresa;
    private javax.swing.JLabel labTitulo;
    // End of variables declaration//GEN-END:variables
}
